// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	endpoint "github.com/fb-investments/aone_location_service/pkg/endpoint"
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	http1 "net/http"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := mux.NewRouter()
	makeListCountriesHandler(m, endpoints, options["ListCountries"])
	makeCreateCountriesHandler(m, endpoints, options["CreateCountries"])
	makeListStatesHandler(m, endpoints, options["ListStates"])
	makeCreateStatesHandler(m, endpoints, options["CreateStates"])
	makeListCityHandler(m, endpoints, options["ListCity"])
	makeCreateCityHandler(m, endpoints, options["CreateCity"])
	return m
}
