// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	endpoint "github.com/fb-investments/aone-location-service/pkg/endpoint"
	pb "github.com/fb-investments/aone-location-service/pkg/grpc/pb"
	grpc "github.com/go-kit/kit/transport/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	listCountries   grpc.Handler
	createCountries grpc.Handler
	listStates      grpc.Handler
	createStates    grpc.Handler
	listCity        grpc.Handler
	createCity      grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.LocationServer {
	return &grpcServer{
		createCity:      makeCreateCityHandler(endpoints, options["CreateCity"]),
		createCountries: makeCreateCountriesHandler(endpoints, options["CreateCountries"]),
		createStates:    makeCreateStatesHandler(endpoints, options["CreateStates"]),
		listCity:        makeListCityHandler(endpoints, options["ListCity"]),
		listCountries:   makeListCountriesHandler(endpoints, options["ListCountries"]),
		listStates:      makeListStatesHandler(endpoints, options["ListStates"]),
	}
}
