// Code generated by protoc-gen-go. DO NOT EDIT.
// source: location.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListCountriesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCountriesRequest) Reset()         { *m = ListCountriesRequest{} }
func (m *ListCountriesRequest) String() string { return proto.CompactTextString(m) }
func (*ListCountriesRequest) ProtoMessage()    {}
func (*ListCountriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{0}
}

func (m *ListCountriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCountriesRequest.Unmarshal(m, b)
}
func (m *ListCountriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCountriesRequest.Marshal(b, m, deterministic)
}
func (m *ListCountriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCountriesRequest.Merge(m, src)
}
func (m *ListCountriesRequest) XXX_Size() int {
	return xxx_messageInfo_ListCountriesRequest.Size(m)
}
func (m *ListCountriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCountriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCountriesRequest proto.InternalMessageInfo

type ListCountriesReply struct {
	Data                 []*Country `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Status               bool       `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string     `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error                *Error     `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListCountriesReply) Reset()         { *m = ListCountriesReply{} }
func (m *ListCountriesReply) String() string { return proto.CompactTextString(m) }
func (*ListCountriesReply) ProtoMessage()    {}
func (*ListCountriesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{1}
}

func (m *ListCountriesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCountriesReply.Unmarshal(m, b)
}
func (m *ListCountriesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCountriesReply.Marshal(b, m, deterministic)
}
func (m *ListCountriesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCountriesReply.Merge(m, src)
}
func (m *ListCountriesReply) XXX_Size() int {
	return xxx_messageInfo_ListCountriesReply.Size(m)
}
func (m *ListCountriesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCountriesReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListCountriesReply proto.InternalMessageInfo

func (m *ListCountriesReply) GetData() []*Country {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ListCountriesReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *ListCountriesReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ListCountriesReply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type CreateCountriesRequest struct {
	Data                 *Country `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCountriesRequest) Reset()         { *m = CreateCountriesRequest{} }
func (m *CreateCountriesRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCountriesRequest) ProtoMessage()    {}
func (*CreateCountriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{2}
}

func (m *CreateCountriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCountriesRequest.Unmarshal(m, b)
}
func (m *CreateCountriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCountriesRequest.Marshal(b, m, deterministic)
}
func (m *CreateCountriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCountriesRequest.Merge(m, src)
}
func (m *CreateCountriesRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCountriesRequest.Size(m)
}
func (m *CreateCountriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCountriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCountriesRequest proto.InternalMessageInfo

func (m *CreateCountriesRequest) GetData() *Country {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateCountriesReply struct {
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error                *Error   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCountriesReply) Reset()         { *m = CreateCountriesReply{} }
func (m *CreateCountriesReply) String() string { return proto.CompactTextString(m) }
func (*CreateCountriesReply) ProtoMessage()    {}
func (*CreateCountriesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{3}
}

func (m *CreateCountriesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCountriesReply.Unmarshal(m, b)
}
func (m *CreateCountriesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCountriesReply.Marshal(b, m, deterministic)
}
func (m *CreateCountriesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCountriesReply.Merge(m, src)
}
func (m *CreateCountriesReply) XXX_Size() int {
	return xxx_messageInfo_CreateCountriesReply.Size(m)
}
func (m *CreateCountriesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCountriesReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCountriesReply proto.InternalMessageInfo

func (m *CreateCountriesReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *CreateCountriesReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateCountriesReply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ListStatesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStatesRequest) Reset()         { *m = ListStatesRequest{} }
func (m *ListStatesRequest) String() string { return proto.CompactTextString(m) }
func (*ListStatesRequest) ProtoMessage()    {}
func (*ListStatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{4}
}

func (m *ListStatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStatesRequest.Unmarshal(m, b)
}
func (m *ListStatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStatesRequest.Marshal(b, m, deterministic)
}
func (m *ListStatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStatesRequest.Merge(m, src)
}
func (m *ListStatesRequest) XXX_Size() int {
	return xxx_messageInfo_ListStatesRequest.Size(m)
}
func (m *ListStatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListStatesRequest proto.InternalMessageInfo

type ListStatesReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStatesReply) Reset()         { *m = ListStatesReply{} }
func (m *ListStatesReply) String() string { return proto.CompactTextString(m) }
func (*ListStatesReply) ProtoMessage()    {}
func (*ListStatesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{5}
}

func (m *ListStatesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStatesReply.Unmarshal(m, b)
}
func (m *ListStatesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStatesReply.Marshal(b, m, deterministic)
}
func (m *ListStatesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStatesReply.Merge(m, src)
}
func (m *ListStatesReply) XXX_Size() int {
	return xxx_messageInfo_ListStatesReply.Size(m)
}
func (m *ListStatesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStatesReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListStatesReply proto.InternalMessageInfo

type CreateStatesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStatesRequest) Reset()         { *m = CreateStatesRequest{} }
func (m *CreateStatesRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStatesRequest) ProtoMessage()    {}
func (*CreateStatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{6}
}

func (m *CreateStatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStatesRequest.Unmarshal(m, b)
}
func (m *CreateStatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStatesRequest.Marshal(b, m, deterministic)
}
func (m *CreateStatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStatesRequest.Merge(m, src)
}
func (m *CreateStatesRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStatesRequest.Size(m)
}
func (m *CreateStatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStatesRequest proto.InternalMessageInfo

type CreateStatesReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStatesReply) Reset()         { *m = CreateStatesReply{} }
func (m *CreateStatesReply) String() string { return proto.CompactTextString(m) }
func (*CreateStatesReply) ProtoMessage()    {}
func (*CreateStatesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{7}
}

func (m *CreateStatesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStatesReply.Unmarshal(m, b)
}
func (m *CreateStatesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStatesReply.Marshal(b, m, deterministic)
}
func (m *CreateStatesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStatesReply.Merge(m, src)
}
func (m *CreateStatesReply) XXX_Size() int {
	return xxx_messageInfo_CreateStatesReply.Size(m)
}
func (m *CreateStatesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStatesReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStatesReply proto.InternalMessageInfo

type ListCityRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCityRequest) Reset()         { *m = ListCityRequest{} }
func (m *ListCityRequest) String() string { return proto.CompactTextString(m) }
func (*ListCityRequest) ProtoMessage()    {}
func (*ListCityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{8}
}

func (m *ListCityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCityRequest.Unmarshal(m, b)
}
func (m *ListCityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCityRequest.Marshal(b, m, deterministic)
}
func (m *ListCityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCityRequest.Merge(m, src)
}
func (m *ListCityRequest) XXX_Size() int {
	return xxx_messageInfo_ListCityRequest.Size(m)
}
func (m *ListCityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCityRequest proto.InternalMessageInfo

type ListCityReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCityReply) Reset()         { *m = ListCityReply{} }
func (m *ListCityReply) String() string { return proto.CompactTextString(m) }
func (*ListCityReply) ProtoMessage()    {}
func (*ListCityReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{9}
}

func (m *ListCityReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCityReply.Unmarshal(m, b)
}
func (m *ListCityReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCityReply.Marshal(b, m, deterministic)
}
func (m *ListCityReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCityReply.Merge(m, src)
}
func (m *ListCityReply) XXX_Size() int {
	return xxx_messageInfo_ListCityReply.Size(m)
}
func (m *ListCityReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCityReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListCityReply proto.InternalMessageInfo

type CreateCityRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCityRequest) Reset()         { *m = CreateCityRequest{} }
func (m *CreateCityRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCityRequest) ProtoMessage()    {}
func (*CreateCityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{10}
}

func (m *CreateCityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCityRequest.Unmarshal(m, b)
}
func (m *CreateCityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCityRequest.Marshal(b, m, deterministic)
}
func (m *CreateCityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCityRequest.Merge(m, src)
}
func (m *CreateCityRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCityRequest.Size(m)
}
func (m *CreateCityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCityRequest proto.InternalMessageInfo

type CreateCityReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCityReply) Reset()         { *m = CreateCityReply{} }
func (m *CreateCityReply) String() string { return proto.CompactTextString(m) }
func (*CreateCityReply) ProtoMessage()    {}
func (*CreateCityReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{11}
}

func (m *CreateCityReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCityReply.Unmarshal(m, b)
}
func (m *CreateCityReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCityReply.Marshal(b, m, deterministic)
}
func (m *CreateCityReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCityReply.Merge(m, src)
}
func (m *CreateCityReply) XXX_Size() int {
	return xxx_messageInfo_CreateCityReply.Size(m)
}
func (m *CreateCityReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCityReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCityReply proto.InternalMessageInfo

type Country struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	CountryName          string   `protobuf:"bytes,2,opt,name=countryName,proto3" json:"countryName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Country) Reset()         { *m = Country{} }
func (m *Country) String() string { return proto.CompactTextString(m) }
func (*Country) ProtoMessage()    {}
func (*Country) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{12}
}

func (m *Country) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Country.Unmarshal(m, b)
}
func (m *Country) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Country.Marshal(b, m, deterministic)
}
func (m *Country) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Country.Merge(m, src)
}
func (m *Country) XXX_Size() int {
	return xxx_messageInfo_Country.Size(m)
}
func (m *Country) XXX_DiscardUnknown() {
	xxx_messageInfo_Country.DiscardUnknown(m)
}

var xxx_messageInfo_Country proto.InternalMessageInfo

func (m *Country) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Country) GetCountryName() string {
	if m != nil {
		return m.CountryName
	}
	return ""
}

type Error struct {
	UserMessage          string   `protobuf:"bytes,1,opt,name=userMessage,proto3" json:"userMessage,omitempty"`
	InternalMessage      string   `protobuf:"bytes,2,opt,name=internalMessage,proto3" json:"internalMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{13}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetUserMessage() string {
	if m != nil {
		return m.UserMessage
	}
	return ""
}

func (m *Error) GetInternalMessage() string {
	if m != nil {
		return m.InternalMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*ListCountriesRequest)(nil), "pb.ListCountriesRequest")
	proto.RegisterType((*ListCountriesReply)(nil), "pb.ListCountriesReply")
	proto.RegisterType((*CreateCountriesRequest)(nil), "pb.CreateCountriesRequest")
	proto.RegisterType((*CreateCountriesReply)(nil), "pb.CreateCountriesReply")
	proto.RegisterType((*ListStatesRequest)(nil), "pb.ListStatesRequest")
	proto.RegisterType((*ListStatesReply)(nil), "pb.ListStatesReply")
	proto.RegisterType((*CreateStatesRequest)(nil), "pb.CreateStatesRequest")
	proto.RegisterType((*CreateStatesReply)(nil), "pb.CreateStatesReply")
	proto.RegisterType((*ListCityRequest)(nil), "pb.ListCityRequest")
	proto.RegisterType((*ListCityReply)(nil), "pb.ListCityReply")
	proto.RegisterType((*CreateCityRequest)(nil), "pb.CreateCityRequest")
	proto.RegisterType((*CreateCityReply)(nil), "pb.CreateCityReply")
	proto.RegisterType((*Country)(nil), "pb.Country")
	proto.RegisterType((*Error)(nil), "pb.Error")
}

func init() { proto.RegisterFile("location.proto", fileDescriptor_4f0f35158dcf9f2c) }

var fileDescriptor_4f0f35158dcf9f2c = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x3d, 0x6f, 0xa3, 0x40,
	0x10, 0x15, 0xfe, 0x66, 0xb8, 0x3b, 0x8e, 0xc5, 0xe6, 0x10, 0x8d, 0x11, 0x15, 0x95, 0x0b, 0xae,
	0xb9, 0x2b, 0x12, 0x29, 0xb2, 0xa2, 0x34, 0x4e, 0x0a, 0xac, 0xfc, 0x80, 0xb5, 0xbd, 0x8a, 0x90,
	0x30, 0x90, 0xdd, 0xa5, 0xe0, 0x1f, 0xe4, 0x57, 0x47, 0xd1, 0xf2, 0xb9, 0x60, 0xda, 0x74, 0xe6,
	0xcd, 0x7b, 0xb3, 0x33, 0xef, 0x8d, 0x0c, 0xbf, 0xe2, 0xf4, 0x8c, 0x79, 0x94, 0x26, 0xbb, 0x8c,
	0xa6, 0x3c, 0x45, 0x93, 0xec, 0xe4, 0x59, 0xb0, 0x3e, 0x44, 0x8c, 0xef, 0xd3, 0x3c, 0xe1, 0x34,
	0x22, 0x2c, 0x24, 0xef, 0x39, 0x61, 0xdc, 0xfb, 0x50, 0x00, 0x0d, 0x0a, 0x59, 0x5c, 0xa0, 0x2d,
	0xcc, 0x2e, 0x98, 0x63, 0x5b, 0x71, 0xa7, 0xbe, 0x16, 0x68, 0xbb, 0xec, 0xb4, 0xab, 0x18, 0x45,
	0x58, 0x16, 0x90, 0x05, 0x0b, 0xc6, 0x31, 0xcf, 0x99, 0x3d, 0x71, 0x15, 0x7f, 0x15, 0xd6, 0x5f,
	0xc8, 0x86, 0xe5, 0x95, 0x30, 0x86, 0xdf, 0x88, 0x3d, 0x75, 0x15, 0x5f, 0x0d, 0x9b, 0x4f, 0xb4,
	0x85, 0x39, 0xa1, 0x34, 0xa5, 0xf6, 0xcc, 0x55, 0x7c, 0x2d, 0x50, 0x45, 0xcf, 0x47, 0x01, 0x84,
	0x15, 0xee, 0xfd, 0x07, 0x6b, 0x4f, 0x09, 0xe6, 0x64, 0x38, 0xa4, 0x34, 0x8d, 0x32, 0x3a, 0x8d,
	0x17, 0xc1, 0xfa, 0x46, 0x2a, 0xd6, 0xf8, 0x86, 0x29, 0x4d, 0x30, 0x84, 0x5f, 0x47, 0x8e, 0x79,
	0xe7, 0xa2, 0x01, 0xba, 0x0c, 0x66, 0x71, 0xe1, 0x6d, 0xc0, 0xac, 0x46, 0xea, 0x33, 0x4d, 0x30,
	0xfa, 0xb0, 0xe0, 0xd6, 0xf2, 0x7d, 0xc4, 0x8b, 0x86, 0xa7, 0xc3, 0xcf, 0x0e, 0x12, 0x9c, 0x56,
	0x28, 0xb3, 0x0c, 0xd0, 0x65, 0x50, 0xf0, 0xee, 0x60, 0x59, 0x7b, 0x83, 0x7e, 0xc3, 0xf4, 0x35,
	0xba, 0x94, 0xae, 0xa9, 0xa1, 0xf8, 0x89, 0x5c, 0xd0, 0xce, 0x55, 0xf1, 0x05, 0x5f, 0x49, 0x69,
	0x8a, 0x1a, 0xca, 0x90, 0x77, 0x84, 0x79, 0xb9, 0xae, 0xa0, 0xe6, 0x8c, 0xd0, 0xe7, 0xda, 0xa6,
	0xaa, 0x89, 0x0c, 0x21, 0x1f, 0xf4, 0x28, 0xe1, 0x84, 0x26, 0x38, 0x6e, 0x58, 0x55, 0xc3, 0x21,
	0x1c, 0x7c, 0x4e, 0x60, 0x75, 0xa8, 0x6f, 0x12, 0x3d, 0xd4, 0x9b, 0x35, 0x49, 0x21, 0x5b, 0x78,
	0x3c, 0x76, 0x9c, 0x8e, 0x35, 0x52, 0x11, 0xb1, 0x3e, 0xb5, 0x6b, 0xb7, 0x4d, 0x9c, 0xf2, 0x28,
	0x46, 0xcf, 0xc7, 0xb1, 0x47, 0x6b, 0xa2, 0xd1, 0x3f, 0x80, 0x2e, 0x37, 0xb4, 0x69, 0x9e, 0xeb,
	0x45, 0xe6, 0x98, 0x43, 0x58, 0x28, 0xef, 0xe1, 0x87, 0x9c, 0x23, 0xfa, 0xd3, 0xbd, 0xd1, 0x57,
	0x6f, 0x6e, 0x0b, 0x42, 0x1f, 0xc0, 0xaa, 0xc9, 0x17, 0xb5, 0x0f, 0x48, 0xd1, 0x3a, 0x46, 0x1f,
	0xac, 0xa7, 0xed, 0xd2, 0x46, 0x52, 0x63, 0x59, 0x67, 0x0e, 0xe1, 0x2c, 0x2e, 0x4e, 0x8b, 0xf2,
	0x8f, 0xe0, 0xef, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7d, 0xb8, 0x7c, 0xda, 0x1a, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LocationClient is the client API for Location service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LocationClient interface {
	ListCountries(ctx context.Context, in *ListCountriesRequest, opts ...grpc.CallOption) (*ListCountriesReply, error)
	CreateCountries(ctx context.Context, in *CreateCountriesRequest, opts ...grpc.CallOption) (*CreateCountriesReply, error)
	ListStates(ctx context.Context, in *ListStatesRequest, opts ...grpc.CallOption) (*ListStatesReply, error)
	CreateStates(ctx context.Context, in *CreateStatesRequest, opts ...grpc.CallOption) (*CreateStatesReply, error)
	ListCity(ctx context.Context, in *ListCityRequest, opts ...grpc.CallOption) (*ListCityReply, error)
	CreateCity(ctx context.Context, in *CreateCityRequest, opts ...grpc.CallOption) (*CreateCityReply, error)
}

type locationClient struct {
	cc *grpc.ClientConn
}

func NewLocationClient(cc *grpc.ClientConn) LocationClient {
	return &locationClient{cc}
}

func (c *locationClient) ListCountries(ctx context.Context, in *ListCountriesRequest, opts ...grpc.CallOption) (*ListCountriesReply, error) {
	out := new(ListCountriesReply)
	err := c.cc.Invoke(ctx, "/pb.Location/ListCountries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationClient) CreateCountries(ctx context.Context, in *CreateCountriesRequest, opts ...grpc.CallOption) (*CreateCountriesReply, error) {
	out := new(CreateCountriesReply)
	err := c.cc.Invoke(ctx, "/pb.Location/CreateCountries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationClient) ListStates(ctx context.Context, in *ListStatesRequest, opts ...grpc.CallOption) (*ListStatesReply, error) {
	out := new(ListStatesReply)
	err := c.cc.Invoke(ctx, "/pb.Location/ListStates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationClient) CreateStates(ctx context.Context, in *CreateStatesRequest, opts ...grpc.CallOption) (*CreateStatesReply, error) {
	out := new(CreateStatesReply)
	err := c.cc.Invoke(ctx, "/pb.Location/CreateStates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationClient) ListCity(ctx context.Context, in *ListCityRequest, opts ...grpc.CallOption) (*ListCityReply, error) {
	out := new(ListCityReply)
	err := c.cc.Invoke(ctx, "/pb.Location/ListCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationClient) CreateCity(ctx context.Context, in *CreateCityRequest, opts ...grpc.CallOption) (*CreateCityReply, error) {
	out := new(CreateCityReply)
	err := c.cc.Invoke(ctx, "/pb.Location/CreateCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocationServer is the server API for Location service.
type LocationServer interface {
	ListCountries(context.Context, *ListCountriesRequest) (*ListCountriesReply, error)
	CreateCountries(context.Context, *CreateCountriesRequest) (*CreateCountriesReply, error)
	ListStates(context.Context, *ListStatesRequest) (*ListStatesReply, error)
	CreateStates(context.Context, *CreateStatesRequest) (*CreateStatesReply, error)
	ListCity(context.Context, *ListCityRequest) (*ListCityReply, error)
	CreateCity(context.Context, *CreateCityRequest) (*CreateCityReply, error)
}

// UnimplementedLocationServer can be embedded to have forward compatible implementations.
type UnimplementedLocationServer struct {
}

func (*UnimplementedLocationServer) ListCountries(ctx context.Context, req *ListCountriesRequest) (*ListCountriesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCountries not implemented")
}
func (*UnimplementedLocationServer) CreateCountries(ctx context.Context, req *CreateCountriesRequest) (*CreateCountriesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCountries not implemented")
}
func (*UnimplementedLocationServer) ListStates(ctx context.Context, req *ListStatesRequest) (*ListStatesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStates not implemented")
}
func (*UnimplementedLocationServer) CreateStates(ctx context.Context, req *CreateStatesRequest) (*CreateStatesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStates not implemented")
}
func (*UnimplementedLocationServer) ListCity(ctx context.Context, req *ListCityRequest) (*ListCityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCity not implemented")
}
func (*UnimplementedLocationServer) CreateCity(ctx context.Context, req *CreateCityRequest) (*CreateCityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCity not implemented")
}

func RegisterLocationServer(s *grpc.Server, srv LocationServer) {
	s.RegisterService(&_Location_serviceDesc, srv)
}

func _Location_ListCountries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCountriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServer).ListCountries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Location/ListCountries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServer).ListCountries(ctx, req.(*ListCountriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Location_CreateCountries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCountriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServer).CreateCountries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Location/CreateCountries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServer).CreateCountries(ctx, req.(*CreateCountriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Location_ListStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServer).ListStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Location/ListStates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServer).ListStates(ctx, req.(*ListStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Location_CreateStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServer).CreateStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Location/CreateStates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServer).CreateStates(ctx, req.(*CreateStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Location_ListCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServer).ListCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Location/ListCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServer).ListCity(ctx, req.(*ListCityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Location_CreateCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServer).CreateCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Location/CreateCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServer).CreateCity(ctx, req.(*CreateCityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Location_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Location",
	HandlerType: (*LocationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCountries",
			Handler:    _Location_ListCountries_Handler,
		},
		{
			MethodName: "CreateCountries",
			Handler:    _Location_CreateCountries_Handler,
		},
		{
			MethodName: "ListStates",
			Handler:    _Location_ListStates_Handler,
		},
		{
			MethodName: "CreateStates",
			Handler:    _Location_CreateStates_Handler,
		},
		{
			MethodName: "ListCity",
			Handler:    _Location_ListCity_Handler,
		},
		{
			MethodName: "CreateCity",
			Handler:    _Location_CreateCity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "location.proto",
}
