// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint "github.com/fb-investments/aone-location-service/pkg/endpoint"
	service "github.com/fb-investments/aone-location-service/pkg/service"
	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	grpc "github.com/go-kit/kit/transport/grpc"
	http "github.com/go-kit/kit/transport/http"
	group "github.com/oklog/oklog/pkg/group"
	opentracinggo "github.com/opentracing/opentracing-go"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initHttpHandler(endpoints, g)
	initGRPCHandler(endpoints, g)
	return g
}
func defaultHttpOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]http.ServerOption {
	options := map[string][]http.ServerOption{
		"CreateCity":      {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "CreateCity", logger))},
		"CreateCountries": {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "CreateCountries", logger))},
		"CreateStates":    {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "CreateStates", logger))},
		"ListCity":        {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "ListCity", logger))},
		"ListCountries":   {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "ListCountries", logger))},
		"ListStates":      {http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "ListStates", logger))},
	}
	return options
}
func defaultGRPCOptions(logger log.Logger, tracer opentracinggo.Tracer) map[string][]grpc.ServerOption {
	options := map[string][]grpc.ServerOption{
		"CreateCity":      {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "CreateCity", logger))},
		"CreateCountries": {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "CreateCountries", logger))},
		"CreateStates":    {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "CreateStates", logger))},
		"ListCity":        {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "ListCity", logger))},
		"ListCountries":   {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "ListCountries", logger))},
		"ListStates":      {grpc.ServerErrorLogger(logger), grpc.ServerBefore(opentracing.GRPCToContext(tracer, "ListStates", logger))},
	}
	return options
}
func addDefaultEndpointMiddleware(logger log.Logger, duration *prometheus.Summary, mw map[string][]endpoint1.Middleware) {
	mw["ListCountries"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "ListCountries")), endpoint.InstrumentingMiddleware(duration.With("method", "ListCountries"))}
	mw["CreateCountries"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "CreateCountries")), endpoint.InstrumentingMiddleware(duration.With("method", "CreateCountries"))}
	mw["ListStates"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "ListStates")), endpoint.InstrumentingMiddleware(duration.With("method", "ListStates"))}
	mw["CreateStates"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "CreateStates")), endpoint.InstrumentingMiddleware(duration.With("method", "CreateStates"))}
	mw["ListCity"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "ListCity")), endpoint.InstrumentingMiddleware(duration.With("method", "ListCity"))}
	mw["CreateCity"] = []endpoint1.Middleware{endpoint.LoggingMiddleware(log.With(logger, "method", "CreateCity")), endpoint.InstrumentingMiddleware(duration.With("method", "CreateCity"))}
}
func addDefaultServiceMiddleware(logger log.Logger, mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware(logger))
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"ListCountries", "CreateCountries", "ListStates", "CreateStates", "ListCity", "CreateCity"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
